name: ijon at c-base
favicon: null
layout_spectrum: 0.23276
typography_spectrum: 0.03448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151c22'
    - '#202d35'
    - '#000000'
    - '#323d3f'
    - '#40545f'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: awareness
    item: null
    url: null
